-- MySQL Script generated by MySQL Workbench
-- 07/06/15 20:27:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table "member"
-- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS  "member" (
    "id" serial NOT NULL ,
    "first_name" VARCHAR(80) NOT NULL ,
    "last_name" VARCHAR(80) NOT NULL ,
    "member_num" serial NOT NULL ,
    "email" VARCHAR(80) NOT NULL ,
    "referer_member_num" INTEGER NOT NULL ,
    PRIMARY KEY ("id")
  );


  2 147 483 647
